Updated Readme file(#2q9nxqt)
hotwax/shopify-admin-helper pull request #18
Opened 2022-08-16 11:30 UTC by azkyakhan

2022-08-16 12:15 UTC, ymaheshwari1 requested changes

2022-08-16 12:15 UTC, ymaheshwari1 commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
Update this link to admin-helper repo.

2022-08-16 12:15 UTC, ymaheshwari1 commented on .github/workflows/pull-request.yml
> +      - master
```suggestion
      - main
```

2022-08-16 12:15 UTC, ymaheshwari1 commented on README.md
> +`npm i
```suggestion
`npm i`
```

2022-08-16 12:15 UTC, ymaheshwari1 commented on README.md
> +6. Use [Pull Request template](https://github.com/hotwax/preorder/blob/main/.github/PULL_REQUEST_TEMPLATE.md) (it's automatically added to each PR) and fill as much fields as possible to describe you
Update the link.

2022-08-16 12:15 UTC, ymaheshwari1 commented on README.md
> +Pre-order app is completely free and released under the Apache v2.0 License. Check <a href="https://github.com/hotwax/shopify-admin-helper/blob/main/LICENSE" target="_blank">LICENSE</a> for more deta
```suggestion
Shopify Admin Helper app is completely free and released under the Apache v2.0 License. Check <a href="https://github.com/hotwax/shopify-admin-helper/blob/main/LICENSE" target="_blank">LICENSE</a> for more details.
```

2022-08-16 12:30 UTC, azkyakhan commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)
Updated Sir

2022-08-16 12:30 UTC, azkyakhan commented on .github/workflows/pull-request.yml
> +      - master
Replaced master with main

2022-08-16 12:32 UTC, azkyakhan commented on README.md
> +6. Use [Pull Request template](https://github.com/hotwax/preorder/blob/main/.github/PULL_REQUEST_TEMPLATE.md) (it's automatically added to each PR) and fill as much fields as possible to describe you
Updated it Sir

2022-08-16 12:32 UTC, azkyakhan commented on README.md
> +Pre-order app is completely free and released under the Apache v2.0 License. Check <a href="https://github.com/hotwax/shopify-admin-helper/blob/main/LICENSE" target="_blank">LICENSE</a> for more deta
Improved app name

2022-08-24 05:54 UTC, adityasharma7 approved these changes

2022-08-24 05:54 UTC, merged