Implemented: functionality to undo order edits (#85zru5e18)
hotwax/shopify-admin-helper pull request #25
Opened 2023-03-29 11:05 UTC by k2maan

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/shopify-admin-helper/blob/main/CONTRIBUTING.md)

2023-03-29 13:01 UTC, adityasharma7 requested changes

2023-03-29 13:01 UTC, adityasharma7 commented on src/views/PickupLocationModal.vue
> +          const inventoryDetails = storesWithInventory.filter((store: any) => store.facilityId === storeData.storeCode);
```suggestion
          const inventoryDetails = storesWithInventory.find((store: any) => store.facilityId === storeData.storeCode);
```

2023-03-30 09:29 UTC, k2maan commented on src/views/PickupLocationModal.vue
> +        if (storeLookupResp.status !== 200 || hasError(storeLookupResp) || !storeLookupResp.data.response.numFound) {
`storeLookup` does not return any errors in case of failure. We can check for `!storeLookupResp.data.response.numFound`

2023-03-30 09:29 UTC, k2maan commented on src/views/PickupLocationModal.vue
> +        if (locationResp.status !== 200 || hasError(locationResp) || !locationResp.data.response.numFound) {
For a failed call it does not return the response field, hence, we can only check for `!locationResp.response` for error. It does not return any fields specified in the `hasError` code on failure.

2023-03-30 09:29 UTC, k2maan commented on src/views/PickupLocationModal.vue
> +        if (hasError(productInventoryResp) || !productInventoryResp.data.count) {
The count is needed sir, as the checkInventory API does not return any error message.

2023-03-30 09:40 UTC, k2maan commented on src/views/PickupLocationModal.vue
> +        if (locationResp.status !== 200 || hasError(locationResp) || !locationResp.data.response.numFound) {
In case of error, `postcodeLookup` returns an error field and omits the response field. So, I've added a check for `!locationResp.response`

2023-03-30 13:04 UTC, merged